# Generated by Django 4.0 on 2021-12-27 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Обо мне', 'verbose_name_plural': 'Обо мне'},
        ),
        migrations.AlterModelOptions(
            name='contactlink',
            options={'verbose_name': 'Мой контакт', 'verbose_name_plural': 'Мои контакты'},
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Форма обратной связи'},
        ),
        migrations.AlterModelOptions(
            name='imageabout',
            options={'verbose_name': 'Изображение обо мне', 'verbose_name_plural': 'Изображине обо мне'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Социальная сеть', 'verbose_name_plural': 'Социальные сети'},
        ),
    ]
